# Generated by Django 3.2.25 on 2024-06-23 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemaintenance',
            name='change_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
