# Generated by Django 4.2.13 on 2024-08-05 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlsheet',
            name='check_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='scandetails',
            name='operator_sign',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='controlsheet',
            name='check_date',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='controlsheet',
            name='signature',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='controlsheet',
            name='updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='controlsheet',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pausedetails',
            name='pause_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pausedetails',
            name='play_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shiftdetails',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shiftdetails',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shiftdetails',
            name='supervisor_signature',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='timemaintenance',
            name='change_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
