# Generated by Django 3.2.25 on 2024-06-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0002_alter_timemaintenance_change_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlsheet',
            name='updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='controlsheet',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
