# Generated by Django 3.2.25 on 2024-06-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0003_auto_20240623_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftdetails',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shiftdetails',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
