# Generated by Django 3.2.25 on 2024-06-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0004_auto_20240623_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlsheet',
            name='check_date',
            field=models.DateTimeField(),
        ),
    ]
