# Generated by Django 3.2.25 on 2024-06-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0005_alter_controlsheet_check_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scandetails',
            name='operator_sign',
            field=models.TextField(null=True),
        ),
    ]
