# Generated by Django 4.2.13 on 2024-07-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0007_auto_20240707_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlsheet',
            name='check_date',
            field=models.DateField(),
        ),
    ]
