# Generated by Django 4.2.13 on 2024-07-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0008_alter_controlsheet_check_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlsheet',
            name='check_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='controlsheet',
            name='signature',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shiftdetails',
            name='supervisor_signature',
            field=models.TextField(null=True),
        ),
    ]
