# Generated by Django 4.2.13 on 2024-07-26 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0009_alter_controlsheet_check_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlsheet',
            name='check_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
