# Generated by Django 4.2.13 on 2024-07-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0010_alter_controlsheet_check_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlsheet',
            name='check_date',
            field=models.DateTimeField(),
        ),
    ]
