# Generated by Django 4.2.13 on 2024-07-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0011_alter_controlsheet_check_date'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='controlsheet',
        #     name='check_time',
        #     field=models.TimeField(null=True),
        # ),
    ]
